import React from 'react';
import proj1 from '../Images/proj4.png';
import github from '../Images/github.png';
import proj2 from '../Images/proj5.png'

function Projects() {
  return (
    <div className='col-md-10  offset-sm-1 offset-md-1' style={{'color':'white'}}>
        <h2 className='section-head' >Projects</h2>
        <h5 >Each project is a unique piece of Development</h5>
        <div className="row project-card" style={{'marginTop':'40px'}}>
            <div className="col-12">
                 <div className="row mt-3 mb-3" >
                  <div className="col-md-5 align-self-center "  style={{'textAlign':'center'}}><img className='project-img' src={proj1} />

                  </div>
                  <div className="col-md-6">
                  <h4>User Authentication/Form Validation</h4>
                  <p>The website allows the Users the features of Registration and signup</p>
                  <ol>
                    <li>Feature for Sign in and Sign up for the user</li>
                    <li>Hashing the password generated by the user.</li>
                    <li>Generating the Sign-in token for user authentication.</li>
                    <li>Storing the token in cookies</li>
                    <li>Technology Used:  
                      <ul>
                         <li><b>ReactJs:</b> Frontend</li>
                         <li><b>ExpressJs:</b> For managing Server and Routes</li>
                         <li><b>MongoDB Atlas:</b> As a cloud database</li>
                          <li><b>Postman:</b> For API testing</li>
                      </ul></li>
                    
                  </ol>
                  <div style={{'paddingLeft':'30%'}}>
                    <a href="https://github.com/ravi18477/Authentication_App/tree/8c944086f5f4e916f4e8f59306f16346bfea862f" target="_blank"><span className='code-Link'>Code link  <span>< img  src= {github}alt="" style={{'width':'15px'}} /></span></span></a>
                    </div>

                  </div>
                      
                 </div>
            </div>
        
        </div>
        <div className="row project-card" style={{'marginTop':'40px'}}>
            <div className="col-12">
                 <div className="row mt-3 mb-3" >
                  
                  <div className="col-md-6">
                  <h4>Landing Page for GYM</h4>
                  <p>The Gym website is an online platform that allows user to buy gym memberships for Training and Yoga Exercises. the website provides an interface for Gym management and Marketing </p>
                  
                    Technology Used:  
                      <ul>
                         <li><b>HTML</b></li>
                         <li><b>CSS</b></li>
                         <li><b>JavaScript</b></li>
                          
                      </ul>
                    
            
                  <div style={{'paddingLeft':'30%'}}>
                   <a href="https://github.com/ravi18477/Landing_Page/tree/20c726159e8fb790c1523ed9cc5a9028c8ffd6ec" target="_blank"> <span className='code-Link'>Code link  <span>< img  src= {github}alt="" style={{'width':'15px'}} /></span></span></a>
                    </div>

                  </div>
                  <div className="col-md-5 align-self-center "  style={{'textAlign':'center'}}><img className='project-img' src={proj2} />

                  </div>
                      
                 </div>
            </div>
        
        

        </div>


      
    </div>
  )
}

export default Projects
